### ISSUE TITLE
Add support to add/update facility's primary phone number

### ISSUE THREAD

**Issue by ravilodhi** [hotwax/facilities#104]
## What is the motivation for adding/enhancing this feature?
The current facility data setup process has support for setting the Primary Phone Number, We need to give similar support in the facilities app.

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

## Additional information
Here is the reference ticket - https://app.clickup.com/t/86cu37d4z

**Comment by sanjanashrivastava** [comment]
<img width="294" alt="Create new facility window" src="https://github.com/hotwax/facilities/assets/155512107/9e7a63be-fc8f-47fe-b4cf-be83c8d6d601">
<img width="327" alt="Edit facility address window" src="https://github.com/hotwax/facilities/assets/155512107/87f47f0b-0c09-4be0-8a0f-1e34555fd73a">

Please refer to these images for reference. 
[Adding country code field needs to be discussed]

**Comment by sanjanashrivastava** [comment]
> <img alt="Create new facility window" width="294" src="https://private-user-images.githubusercontent.com/155512107/303626317-9e7a63be-fc8f-47fe-b4cf-be83c8d6d601.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3MTc4MTIsIm5iZiI6MTcwNzcxNzUxMiwicGF0aCI6Ii8xNTU1MTIxMDcvMzAzNjI2MzE3LTllN2E2M2JlLWZjOGYtNDdmZS1iNGNmLWJlODNjOGQ2ZDYwMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMlQwNTU4MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02OTM5MWI4NDMzNGViYWIzMTkzZjJhZjUyNTVkYzU0ZDRiOTc2NWE3MTFmMDllMWVjOGVkYWU5ZGI1OTc0MGQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gRfP_kBxdSLfkHtp2H4HqztDPh02FK9dJDJfs4U1GYY"> <img alt="Edit facility address window" width="327" src="https://private-user-images.githubusercontent.com/155512107/303625623-87f47f0b-0c09-4be0-8a0f-1e34555fd73a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3MTc4MTIsIm5iZiI6MTcwNzcxNzUxMiwicGF0aCI6Ii8xNTU1MTIxMDcvMzAzNjI1NjIzLTg3ZjQ3ZjBiLTBjMDktNGJlMC04YTBmLTFlMzQ1NTVmZDczYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMlQwNTU4MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNDA0OWRiZWMwYmRmYjkwMzIwYmIyMjIyMmMzNDQ4N2YxMWJmY2RmOWEwOTVlZGI0MGFiYTdhZTNjYzVkZWQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.EHaydHWyYNk-GoAClaXSicNjxAlAsS4PS5PnAzENwyQ">
> Please refer to these images for reference. [Adding country code field needs to be discussed]

<img width="412" alt="Filled address" src="https://github.com/hotwax/facilities/assets/155512107/7aa36c58-a472-4362-a718-b683a47c7971">
<img width="350" alt="Address card" src="https://github.com/hotwax/facilities/assets/155512107/78f4f4c4-921e-43a2-b5f9-c3152f7fe049">
