### ISSUE TITLE
Auto focus on facility id modal

### ISSUE THREAD

**Issue by dt2patel** [hotwax/facilities#132]
## What is the motivation for adding/enhancing this feature?

When user is editing or creating new facility ID, the first input field should be auto focused.

<img width="685" alt="Screenshot 2023-12-22 at 3 36 41 PM" src="https://github.com/hotwax/facilities/assets/60128132/99a65023-9ce6-4e33-84af-9ce96b27cb8c">

**Comment by Adameddy26** [comment]
Changes verified and working fine in release v1.9.1. Hence, closing this ticket.
