### ISSUE TITLE
Allowing Users to Set Shipping Name for Facility Address 

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/facilities#154]
## What is the motivation for adding/enhancing this feature?
Currently, when users add a Facility Address, we want to introduce the ability for them to set a custom "Shipping Name" associated with that address. The Shipping Name will be prepopulated with the Product Store Name by default. In cases where multiple product stores exist, we will prepopulate it with the Company Name. Upon saving, this value should be stored in the `toAddress` field of the `PostalAddress` entity for the facility.

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by Adameddy26** [comment]
Verified in release v1.5.0 and found 2 issues in it.
1. Shipping name label text is not properly aligned with its header text while setting up address. Also '-' is appearing preset for contact number.
https://jam.dev/c/9a3985eb-f350-49b1-9c46-8647ce47f3c5
2. User is not able to edit the address and contact details including shipping name if postal code is not provided while creating the respective facility.
https://jam.dev/c/ba06bba9-e337-4245-a5bc-2c174be49251

**Comment by amansinghbais** [comment]
Based on discussion with @Dhiraj1405 sir, we are pre-populating the shipping name with the facility name.

**Comment by Adameddy26** [comment]
Enhancement verified and working fine in release v1.6.0.
Hence, closing it.
https://jam.dev/c/81afea2a-6607-4c5c-bbf8-687553d7f775
https://jam.dev/c/c846e6a5-ba73-437d-8425-1d4a3a755533
