### ISSUE TITLE
Migrate to ionic 7

### ISSUE THREAD

**Issue by ymaheshwari1** [hotwax/facilities#162]

**Comment by Adameddy26** [comment]
It has been observed that while creating a facility, placeholder text of Zipcode is not visible to user which is causing difficulty in identifying the field purpose. Also when left blank, user is getting the error message and not able to create the facility as it is a mandatory field.
https://jam.dev/c/117f207c-4e6e-41e6-a2c7-c12ff43e5a78

Hence, reopening this ticket.

**Comment by Adameddy26** [comment]
> It has been observed that while creating a facility, placeholder text of Zipcode is not visible to user which is causing difficulty in identifying the field purpose. Also when left blank, user is getting the error message and not able to create the facility as it is a mandatory field. https://jam.dev/c/117f207c-4e6e-41e6-a2c7-c12ff43e5a78
> 
> Hence, reopening this ticket.

Issue verified and working fine in release v1.6.1. Hence, closing this ticket.
https://jam.dev/c/6df757dd-bd8f-455e-b7e7-a94d6b40c391

**Comment by Adameddy26** [comment]
https://jam.dev/c/71d02cad-ea25-4cf9-aec6-54935d791877

<br> tag issue in alert is working fine in latest release v1.7.0.
