### ISSUE TITLE
Search on groups page changes the UI

### ISSUE THREAD

**Issue by ymaheshwari1** [hotwax/facilities#165]
## Current behavior

When searching for some group on the find groups page, if there are less results than extra space gets added in the UI.

## Expected behavior

The UI should not change in case of searching.

## Steps to reproduce the issue

- Go to find groups page
- Search for a keyword for which less search results are expected
- See that the extra space is present between the cards

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version: 

## Additional information

![image](https://github.com/hotwax/facilities/assets/41404838/95abe99d-d1ef-4f18-a071-90a308c95590)

**Comment by dt2patel** [comment]
Need to add align-items: start on the "find" class div/container in the app themes project (actual code location could vary, not 100% sure)

**Comment by Adameddy26** [comment]
Verified and working fine in release v1.9.0. Hence ,closing it.
