### ISSUE TITLE
`Add new parking` should be FAB

### ISSUE THREAD

**Issue by ymaheshwari1** [hotwax/facilities#166]
## Current behavior

When the `Add new parking` card is in left column then it looks as expected, but when the card is in the right column the card height changes.

## Expected behavior

The card should be display same in both the columns.

## Steps to reproduce the issue

- Go to parking page
- See that how the card looks in the left column, if present or in right column
- Archive a parking or add a new parking so the card changes its position and now see the changes in UI.

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version: 

## Additional information

![image](https://github.com/hotwax/facilities/assets/41404838/24be37ef-9841-43ea-a397-a5160acf2e42)

![image](https://github.com/hotwax/facilities/assets/41404838/be6eac1d-45ee-48ab-80d8-29914035ec4b)

**Comment by dt2patel** [comment]
Switch from this UI to traditional FAB pattern for consistency

**Comment by Adameddy26** [comment]
Issue verified and working fine in v1.4.0.
https://jam.dev/c/d7a99cad-f43b-43c4-bb2c-0f51c6e2122c
