### ISSUE TITLE
Empty state for `Sell inventory online` card

### ISSUE THREAD

**Issue by ymaheshwari1** [hotwax/facilities#167]
## Current behavior

In case when the facility does not have any channels linked to it, the card just displayed the title and description and it becomes confusing for the user, as the card says to select a channel but there is no option to select.

## Expected behavior

Either the card should be hidden when facility is not linked to any channel or the description of the card should be changed.

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version: 

## Additional information

![image](https://github.com/hotwax/facilities/assets/41404838/df0b9519-7e18-4a2b-8931-1d372243b9d4)

**Comment by amansinghbais** [comment]
Empty state message: "No channels found for publishing inventory."
