### ISSUE TITLE
Remove Shopify frontend link on facility details 

### ISSUE THREAD

**Issue by sanjanashrivastava** [hotwax/facilities#174]
## Current behavior
Both the frontend and backend links for Shopify store are present on the Shopify card under the external mappings tab on Facility details page. There is no use case for the frontend link here. It can be removed from the card for simplifying the UI. Please see the screenshot attached for more clarity. 

## Expected behavior
Frontend link can be removed from the card for simplifying the UI.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version: 

## Additional information

<img width="368" alt="Screenshot 2024-01-12 at 6 12 36 PM" src="https://github.com/hotwax/facilities/assets/155512107/117abea6-f80c-4421-90a1-dd39142a4e33">

**Comment by Adameddy26** [comment]
Verified and working fine in v1.4.0.
https://jam.dev/c/a8162164-6836-473b-9bfb-0830bfc9adab
