### ISSUE TITLE
Improve Create Parking workflow to show clear error message while creating parking with duplicate facility ID.

### ISSUE THREAD

**Issue by ravilodhi** [hotwax/facilities#185]
## What is the motivation for adding/enhancing this feature?
Currently, if we create a parking facility with a duplicate internal ID (facility ID), we receive an error toast with the message 'Failed to create parking.' It would be great if the user could see the exact reason, such as 'Facility with ID already exists.'

Additionally, automatically generate an internal ID if the user removes it manually from the Create Parking form.

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by amansinghbais** [comment]
Based on discussion, we will be showing error message from server dynamically in case of facility creation failure due to duplicate facilityId.

**Comment by Adameddy26** [comment]
Verified and working fine in release v1.9.0. Hence, closing it.
