### ISSUE TITLE
Facilities list is not visible

### ISSUE THREAD

**Issue by ymaheshwari1** [hotwax/facilities#187]
## Current behavior

When login into specific oms, facilities count is visible on the home page but facilities list is not visible.

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by amansinghbais** [comment]
Facilities list is not loading because the 'FACILITYVIEW' entity is missing from the specific instance. The app will work fine when new update comes of the instance.
