### ISSUE TITLE
Display facility group name instead of facility group ID

### ISSUE THREAD

**Issue by ravilodhi** [hotwax/facilities#188]
## Current behavior
Currently Facility Group ID is displayed in the group drop-down in the system groups panel on Find Groups page.

## Steps to reproduce the issue
1) Go to /find-groups
2) In the left panel "System Groups" check the dropdown.
3) Currently Facility Group ID is displayed instead of Facility Group Name.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version: 

## Additional information
![Uploading Facilities_groups.png…]()

**Comment by Adameddy26** [comment]
Verified and working fine in release v1.9.0. Hence, closing it.
