### ISSUE TITLE
Facility Not Disassociating When Unchecked in Quick Edit

### ISSUE THREAD

**Issue by Amir-HC** [hotwax/facilities#206]
__Current Behavior:__
When attempting to disassociate a facility from a facility group by unchecking the associated checkbox in the quick edit mode, the facility remains associated despite the checkbox being unchecked. Additionally, the toast notification erroneously indicates that the association was successful.

__Expected Behavior:__
The facility should be successfully disassociated from the facility group when the associated checkbox is unchecked in the quick edit mode. The toast notification should accurately reflect the status of the disassociation process.

__Steps to Reproduce the Issue:__
1. Click on the quantity on the facility card.
2. Select "Quick Edit" from the options.
3. Uncheck the checkbox corresponding to the facility that needs to be disassociated.
4. Save the association changes

Watch the screen recording here: https://jam.dev/c/5acb682b-f7a3-4de1-8a23-4b11636ae183

-------------------------------------

**Website URL:**
[https://facilities.hotwax.io/find-groups](https://facilities.hotwax.io/find-groups)

**Device and browser info:**
Chrome 120.0.6099.199 (1440x813) | Mac OS (arm) 10.15.7

**Date and time:**
February 21st 2024 | 2:04pm UTC

**View developer information (console logs, network requests & timing):**
[jam.dev/c/5acb682b-f7a3-4de1-8a23-4b11636ae183](https://jam.dev/c/5acb682b-f7a3-4de1-8a23-4b11636ae183)

-------------------------------------

*Captured with* *[jam.dev](https://jam.dev?utm_source=github&utm_medium=integration&utm_campaign=captured_with_link_2022_11)*

**Comment by amansinghbais** [comment]
Unable to regenerate this issue.
