### ISSUE TITLE
switch to tabs navigation

### ISSUE THREAD

**Issue by dt2patel** [hotwax/facilities#207]
## What is the motivation for adding/enhancing this feature?

The cards navigation sucks. Let's just go back to tabs. 

Facilities, Parking, Groups, Settings. Persist the navigation on all detail pages as well.

**Comment by Adameddy26** [comment]
Issue verified and working fine in v1.4.0.
https://jam.dev/c/73d94f13-3877-492f-854a-1e75cd0ce507
