### ISSUE TITLE
Directly change group type from group card

### ISSUE THREAD

**Issue by dt2patel** [hotwax/facilities#208]
## What is the motivation for adding/enhancing this feature?

The group card overflow menu should have an option to edit the type of a group. Clicking on "Set type" will open a menu with all group types and a radio select option. Types will be grouped by parent type. Not sure if parent type ever needs to be selected directly.

https://www.figma.com/file/bVPRRw282CqGKMdbz7dciH/HC-Ionic-design-system?type=design&node-id=34753-98944&mode=design&t=XWwiAWPG23MiIIFQ-11

**Comment by Adameddy26** [comment]
Verified and working fine in v1.4.0. 
https://jam.dev/c/63c9e5fe-6ec9-4365-b749-2fa18543518c
