### ISSUE TITLE
Link group to product store

### ISSUE THREAD

**Issue by dt2patel** [hotwax/facilities#210]
## What is the motivation for adding/enhancing this feature?

Add option link a facility group to product stores, similar to how facilities are linked to groups. Clicking on chip directly opens modal with product stores with check boxes. Clicking on save from modal updates assoc.

Product stores
Overline
Product Store Name
note
Item
Select
Product Store ID
Item
Secondary text 2
Item

**Comment by Adameddy26** [comment]
Verified and working fine in v1.4.0.
https://jam.dev/c/ca95d1c9-c859-4c2b-8af0-332178f6129f
