### ISSUE TITLE
All facilities not showing up in select facilities modal in facility group card.

### ISSUE THREAD

**Issue by amansinghbais** [hotwax/facilities#220]
## Current behavior

Currently some facilities are not showing in select facilities modal in facility group card after they are disassociated from a group.

## Expected behavior

All facilities should be shown in select facilities modal in facility group card.

## Steps to reproduce the issue

- Go to select facilities modal from facility group card.
- Associate and then disassociate any facility to any of the group.
- Close and reopen that modal again.
- Verify, that facility is not present in the modal.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by Adameddy26** [comment]
Issue verified and working fine in facilities app release v1.5.0.
https://jam.dev/c/12ffa2b3-0b54-4a69-af97-1cda5faa9004
