### ISSUE TITLE
Unable to redirect to the find facilities page from details page

### ISSUE THREAD

**Issue by ymaheshwari1** [hotwax/facilities#222]
## Current behavior

When on details page and then clicking the back button, the user is landed on a blank page instead of moving to the list page

## Expected behavior

On clicking back button the user should always move to the find facilities page

## Steps to reproduce the issue

1. Go to detail page of any facility
2. Refresh the page
3. Click the back button and check that the list page is not visible

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version: 

## Additional information

Also check for any redirections inside the app and update them.

**Comment by Adameddy26** [comment]
Verified and working fine in release v1.9.3. Hence, closing this ticket.
