### ISSUE TITLE
Clicking save in the facility group type selector without making any change should not display the toast message

### ISSUE THREAD

**Issue by ymaheshwari1** [hotwax/facilities#224]
## Current behavior

For any group, when changing the groupType, clicking save button without making any change inside the modal displays a success toast.

## Expected behavior

If there is no change in the type for a group then we should not display a toast message.

## Steps to reproduce the issue

1. Go to facility group page
2. Click options icons and select `select type`
3. Click save button without making any change in the group type
4. Verify that the success toast is being displayed

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version: 

## Additional information

We should disable the button if there is no change in the groupType for the group.

**Comment by Adameddy26** [comment]
Issue verified and working fin in release v1.5.0.
https://jam.dev/c/b6bcfcd0-4f43-49c3-b007-540dee0cd676
