### ISSUE TITLE
Duplicate virtual facilities are displayed on parking page

### ISSUE THREAD

**Issue by ymaheshwari1** [hotwax/facilities#235]
## Current behavior

In some case when the same virtual facility is associated with multiple productStores then the facilities are displayed twice

## Expected behavior

The parking facilities should not be duplicate in any case

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version: 

## Additional information

Screenshot:

![image](https://github.com/hotwax/facilities/assets/41404838/ce20a2fe-e01b-4a22-b652-5dc948a2ad5e)

**Comment by Adameddy26** [comment]
Issue verified and working fine in release v1.6.0. 
Hence, closing it.
https://jam.dev/c/ec1ab3ca-f61d-40a8-8b55-88da806130cc
