### ISSUE TITLE
When scrolling the page where infinite scroll is used, the page displays empty state if api fails while loading more data

### ISSUE THREAD

**Issue by ymaheshwari1** [hotwax/facilities#241]
## Current behavior

When scrolling the page where infinite scroll is used, the page displays empty state if api fails while loading more data.

This issue can be generated on all pages when inifinite scroll is implemented.

## Expected behavior

The previously loaded data should not be cleared if a corresponding api fails.

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version: 

## Additional information

Reference Issue: https://github.com/hotwax/users/issues/211

**Comment by Adameddy26** [comment]
Issue verified and working fine in release v1.6.1. Hence, closing this ticket.
https://jam.dev/c/3d4c8f2e-8397-498e-a8c6-1d5d0ad8705f
