### ISSUE TITLE
Support Facility Sequencing within Facility Groups

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/facilities#249]
## Description
Currently, the Facilities app does not support sequencing or custom ordering of facilities within facility groups. This enhancement aims to introduce a feature that enables users to specify the order or sequence in which facilities appear within their respective facility groups.

**Comment by dt2patel** [comment]
A group detail page where users can also add custom sequence to a list of facilities.

**Comment by ravilodhi** [comment]
This will be handled under #293 . Closing this ticket.
