### ISSUE TITLE
Incomplete visibility of Facilities in select Facilities modal

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/facilities#254]
## Expected behavior
All facilities available for selection should be fully visible within the modal without the need for excessive scrolling.

## Steps to reproduce the issue
Login the app with valid user credentials.
Go to Groups tab.
For any group, open the select facilities modal.
Scroll through the list of facilities available for selection.
Notice that not all facilities are visible within the modal.

## Environment details
App version : V1.7.0
App environment : UAT

## Additional information
https://jam.dev/c/3c818cc2-edfc-4993-a3db-85e22c1b6834

**Comment by dt2patel** [comment]
Same as this ticket #274 , closing other task

**Comment by ravilodhi** [comment]
This will be covered in the new UI of facility groups under #293 . Closing this ticket.
