### ISSUE TITLE
UI Issues related to group type labels under 'Groups' section in facility details page.

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/facilities#258]
## Current Behavior
When clicking the 'Link to Groups' button under the 'Groups' section on the facility details page, a modal opens displaying all facility group names. In this modal, the group type is shown as 'null' for facility groups that are not linked to any specific type.
Additionally, under the 'Groups' section where linked groups are displayed, the label for the group type appears truncated for most facility groups.

## Expected Behavior
The modal should display accurate group types or indicate clearly when some groups are not linked to any type (e.g., displaying 'Unlinked' instead of 'null').
Group type labels under the 'Groups' section should be fully visible without truncation.

## Steps to reproduce the issue
Navigate to the facility details page.
Under the 'Groups' section.
Check for linked groups and notice truncated group type labels.
Click the 'Link to Groups' button.
Observe the modal displaying 'null' as group type for unlinked facility groups.

## Environment details
App version : v1.7.0
App environment : UAT

## Additional information
https://jam.dev/c/e9760f1b-aa18-4ffa-8da3-eb7ee2170d5e

**Comment by dt2patel** [comment]
Skip the truncation issue for now. I need to revise the UI for that

**Comment by priyanshee1604** [comment]
Verified the issue on the demo instance by creating a Facility Group without a linked type(FacilityGroupType). On the UI, it is correctly listed under the "Others" heading. However, the issue with the truncated group label name still persists.
