### ISSUE TITLE
UI Discrepancy with Facility Count and Linked Facilities in Facility Group

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/facilities#260]
## Expected behavior
Need to be discussed

## Steps to reproduce the issue
Open the facility group tab.
Observe the facility count chip displayed for a specific facility group.
Click to view the linked facilities of the same facility group.
Notice the discrepancy between the total facility count and the number of linked facilities displayed (excluding virtual facilities).

## Environment details
App version : V1.7.0
App environment : UAT

## Additional information
https://jam.dev/c/66922a65-51ce-4667-b39b-6156a9267174

**Comment by amansinghbais** [comment]
Here in this issue, the facilities displayed in the "Find Facilities" section are retrieved using the "FacilityView" entity. This entity is filtered by facilityTypeId and parentFacilityTypeId to exclude virtual facilities, ensuring that only non-virtual facilities are shown.

However, when fetching the count of facilities associated with groups, we use the "FacilityGroupAndMember" entity. This entity does not support filtering by facilityTypeId and parentFacilityTypeId. As a result, we cannot exclude virtual facilities, leading to a facility count for a group that includes virtual facilities.

After discussing this, we concluded that we need to either identify an alternative entity or enhance the "FacilityGroupAndMember" entity to support filtering by facilityTypeId and parentFacilityTypeId. This will enable us to fetch facility counts that exclude virtual facilities.

**Comment by Dhiraj1405** [comment]
Will add UI here

**Comment by ravilodhi** [comment]
This will be resolved with the new UI of facility groups that will be covered under #293. Closing this ticket.
