### ISSUE TITLE
Add support for redirection from Company app on find page with productStore filter applied

### ISSUE THREAD

**Issue by amansinghbais** [hotwax/facilities#267]
## What is the motivation for adding/enhancing this feature?

We want to redirect user to the facilities list page with the productStoreId filter applied when redirecting from the company app for a particular product store.

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by Adameddy26** [comment]
Verified and working fine in release v1.8.0. Hence, closing it.
