### ISSUE TITLE
Keep the toggles in their original state on opening the facility details page

### ISSUE THREAD

**Issue by Chinmay2107** [hotwax/facilities#271]
## Current behavior
When opening any facility on facilities app, all the toggles are by default off. Once refreshed, the toggles are displayed in their original state.

## Expected behavior
The toggles should be displayed in their original state when opening the facility details page.

## Steps to reproduce the issue
Find below the JAM link to reproduce the issue:
https://jam.dev/c/c6c2d708-26d1-48ba-a620-cd89a32297b0

## Environment details
- Browser: Google Chrome, 126
- OS: Ubuntu 22.04 LTS
- Code Version: 1.7.0

**Comment by Adameddy26** [comment]
Verified and working fine in release v1.8.0. Hence, closing it.
