### ISSUE TITLE
Owner party ID issue in Facility App 

### ISSUE THREAD

**Issue by khushalidube** [hotwax/facilities#272]
## Current behavior
The facilities app when creating a new facility places the value for the owner party id as "COMPANY". Since the owner party ID value can vary, for example "NN_COMPANY" and not COMPANY it throws a foreign key constraint error hindering the facility creation through facilities app. 

## Expected behavior
The owner party id should not be hard coded as "COMPANY" instead should be the owner of the product store the facility is created for.

<img width="1440" alt="Screenshot 2024-06-20 at 11 43 28 AM" src="https://github.com/hotwax/facilities/assets/169276781/91674e12-9318-45ce-9f9f-0f8398ff8ddd">

## Steps to reproduce the issue
Please provide the steps to reproduce and if possible a *minimal reproducible example* of the problem

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by amansinghbais** [comment]
Following bug is handled in following issue: https://github.com/hotwax/facilities/issues/278

Hence closing it.
