### ISSUE TITLE
Infinite scroll in facility group quick edit

### ISSUE THREAD

**Issue by dt2patel** [hotwax/facilities#274]
## What is the motivation for adding/enhancing this feature?

Infinite scroll seems to not be working when user does a quick edit from the facility group page through the modal.

**Comment by amansinghbais** [comment]
During the initial discussions, we decided not to show all facilities by default and allow user to search facilities and add. Hence we intentionally didn't added the infinite scrolling in the modal. We only added the searching and displayed the total facilities count to keep track.

We can add infinite scrolling in the modal if we want to.

**Comment by dt2patel** [comment]
Ok makes sense, this isn't a blocker issue but we can put on our roadmap.
