### ISSUE TITLE
Make organization partyId dynamic instead of hardcoding it.

### ISSUE THREAD

**Issue by amansinghbais** [hotwax/facilities#278]
## What is the motivation for adding/enhancing this feature?

Currently we are hardcoding the organization partyID as "COMPANY", we should make it dynamic to avoid any errors in case of changes.

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by Adameddy26** [comment]
Verified and working fine in latest release v1.8.2. Hence, closing this ticket
