### ISSUE TITLE
Facility Group Option Not Visible in Order Routing App Filters

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/facilities#281]
## Expected behavior
After linking the product store to the new facility group, the facility group should appear as an option in the filters of the Order Routing application.

## Steps to reproduce the issue
Log in the app with valid user credentials.
Navigate to the facility group section.
Select a facility group that is not currently linked to any product store.
Link the product store to a facility group that was not previously associated with any product store.
Save the changes and navigate to the Order Routing application.
Open any route of any run and then open the filters dropdown.
Take note of dropdown values and observe the issue.

## Environment details
App version : v1.8.2
App environment : UAT

**Comment by ymaheshwari1** [comment]
After debugging its found that its related to timeZone difference of server, it will be fixed once the server timeZones will be synced.

**Comment by Adameddy26** [comment]
Verified and working fine in the latest release i.e. v1.8.2. Hence, closing this ticket.
