### ISSUE TITLE
Facilities list becomes empty if the infinite scroll call fails

### ISSUE THREAD

**Issue by ymaheshwari1** [hotwax/facilities#282]
## Current behavior

When scrolling on the facilities list page, if the infinite scroll call fails then the complete facilities list gets cleared

## Expected behavior

The previously displayed list should not be removed, if the corresponding api call fails.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by Adameddy26** [comment]
Issue verified and working fine in release v1.9.0. Hence, closing it.
https://jam.dev/c/39bfcea6-abe3-4a8f-8a65-e15f3f5fdd9a
