### ISSUE TITLE
Card content is hidden behind the tab-bar

### ISSUE THREAD

**Issue by ymaheshwari1** [hotwax/facilities#289]
## Current behavior

As we have a tab-bar for navigation, the last data on the page is hidden behind the tab.

## Expected behavior

Add padding bottom to ion-content, so that all the data is completly visible

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version: 

## Additional information

Check this in the whole app and add padding to the bottom wherever required.

![image](https://github.com/user-attachments/assets/4267b0bf-7d53-40ca-bdca-16df9efc762d)

**Comment by ymaheshwari1** [comment]
@Ridwan6947 Pick this once next.

**Comment by Adameddy26** [comment]
Issue verified and working fine in release v1.9.1. Hence, closing this issue.
![Screenshot from 2024-08-27 23-46-54](https://github.com/user-attachments/assets/08b4e871-a0a6-4dcb-868d-a5e909fd811c)
