### ISSUE TITLE
Missing Separator Horizontal Line Between Product Stores and Facilities in Groups Tab

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/facilities#291]
## Note
Also there is extra separator horizontal line present at the bottom of few parking cards.

## Current behavior
The separator horizontal line is missing, leading to a lack of visual separation between the "Product Stores" and "Facilities" sections.

## Expected behavior
A clear separator horizontal line should be visible between the "Product Stores" and "Facilities" sections, providing a visual distinction between these sections.

## Steps to reproduce the issue
Open the Facilities app.
Navigate to the "Groups" tab.
Observe the area between the "Product Stores" and "Facilities" sections.

## Environment details
App version : V1.8.2
App environment : UAT

## Additional information
![Screenshot from 2024-07-29 16-30-55](https://github.com/user-attachments/assets/b24ed3a2-6b91-44e8-b933-4405bd13326c)

**Comment by ymaheshwari1** [comment]
@Ridwan6947

**Comment by Adameddy26** [comment]
Verified in release v1.9.0 and found that extra separator horizontal line is still present in the bottom of parking cards. Hence, reopening it.
![Screenshot from 2024-08-20 16-01-12](https://github.com/user-attachments/assets/1a5bf574-9f9a-4c66-bd3a-132c558185c1)

**Comment by Adameddy26** [comment]
Issue verified in release v1.9.2 and found that extra space is visible at the bottom of parking cards. Hence, reopening this issue.

**Comment by dt2patel** [comment]
Correct @Adameddy26  card height should be restricted to the content of the cards. The styling used in the groups page should be mirrored in the parkings page.

**Comment by Adameddy26** [comment]
Verified and working fine in release v1.9.3. Hence, closing this ticket.

![image](https://github.com/user-attachments/assets/c21227c2-e034-4d50-9f5f-ef8144549247)
