### ISSUE TITLE
Enhance Facility Groups page experience and Implement facility sequencing

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/facilities#293]
## What is the motivation for adding/enhancing this feature?
The current Facility Groups page requires improvements to enhance user experience and functionality.

### Key Enhancements:

1. Improve Facility Groups Page: Conduct a thorough UX analysis of the Facility Groups page to identify areas for improvement. This includes layout, navigation, and overall usability.
2. Implement Facility Sequencing: Allow users to define the order in which facilities are displayed within a facility group.

The complete revamp could be time taking, so we can initially move ahead with accommodating the sequencing UI, which look like this: 
<img width="1440" alt="After selection" src="https://github.com/user-attachments/assets/ec87d713-20eb-4574-94f8-6f3b3f099c06">

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

## Additional information
Link to[ UI](https://www.figma.com/design/wK5FMs4z2zXQR9VfHV9ycE/Dhiraj's-Ionic-6-Material-UI-Kit-(Community)?node-id=31870-179986&t=iq9mtpiOVRpiZudb-1)

**Comment by Dhiraj1405** [comment]
Due to performance concerns, making individual API calls for each facility during sequence updates would create unnecessary network traffic and impact system performance. A separate ClickUp ticket (https://app.clickup.com/t/86cw54361) has been created to develop a bulk update functionality. The logic for this page should be updated once that ticket is completed.

**Comment by Adameddy26** [comment]
Sometimes, it's observed that an alert doesn't trigger, and the sequence gets saved when the user tries to go back after saving the sequence for the first time.
https://jam.dev/c/3c0938c1-e9ac-43c9-8fab-42bf9e1f3c9f
