### ISSUE TITLE
Searched keyword persists after saving and reopening the Manage Facilities page

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/facilities#305]
## Current behavior
Upon reopening the page, the facilities corresponding to the previously searched keyword are still visible, and the keyword remains in the search bar.

## Expected behavior
When the page is reopened, all facilities should be listed, and the previously searched keyword should be cleared.

## Steps to reproduce the issue
Navigate to the "Manage Facilities" page.
Enter a keyword in the search bar to filter the facilities.
Select the facilities based on the searched keyword.
Save the changes.
Reopen the "Manage Facilities" page.

## Environment details
App version : v1.9.2
App environment : UAT

## Additional information
https://jam.dev/c/c78d188b-8c3b-410b-858a-fa87823f0a13

**Comment by ravilodhi** [comment]
Will be fixed in the following PR - https://github.com/hotwax/facilities/pull/313

**Comment by Adameddy26** [comment]
Issue verified and working fine in release v1.9.3. Hence, closing this ticket.
https://jam.dev/c/4eb56e68-34ee-4615-8bd7-91eec49f87a3
