### ISSUE TITLE
[Usability]Pressing Enter or Shift+Enter in any input field during facility group creation leads to the next step for creating a facility group

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/facilities#307]
## Note 
Working fine in case of facility creation but not in parking creation.

## Current behavior
Pressing Enter or Shift+Enter unexpectedly advances the process to the next step.

## Expected behavior
Pressing Enter or Shift+Enter should remain within the same input field. It should not trigger navigation to the next step.

## Steps to reproduce the issue
Navigate to the groups page and add button to create new.
Begin entering details into any input field while creating a facility group.
Press the Enter or Shift+Enter key while focused on any input field.
Observe the issue.

## Environment details
App version : v1.9.2
App environment : UAT

## Additional information
https://jam.dev/c/cdd18d04-c361-4f2f-8134-c9fa182d51e0

**Comment by ravilodhi** [comment]
This will be fixed in the following PR - https://github.com/hotwax/facilities/pull/313

**Comment by Adameddy26** [comment]
Verified and working fine in release v1.9.3. Hence, closing this ticket.
https://jam.dev/c/ec8bdd34-57d0-4df1-9f01-2545e8e6367d
