### ISSUE TITLE
Parent Group Association Not Opening After Tab Switching

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/facilities#308]
## Current behavior
The parent group association fails to load or open, leaving the user unable to view or interact with the details.

## Expected behavior
The parent group association should load and be fully functional when the user returns to the original tab.

## Steps to reproduce the issue
Log in to the application.
Navigate to the Groups->Parent Group Association.
Open any parent group to view its details.
Switch to another tab(facilities, settings, parking).
Return to the original tab.
Attempt to open the parent group association of any parent group.
Observe the issue.

## Environment details
App version : v1.9.2
App environment : UAT

## Additional information
https://jam.dev/c/16f1a740-9e54-4f4d-b08d-d6f5206b4cc8

**Comment by ravilodhi** [comment]
This will be fixed in the following PR - https://github.com/hotwax/facilities/pull/313

**Comment by Adameddy26** [comment]
https://jam.dev/c/aae866ad-afcd-40a7-95cb-4bfe6db9fc85
Issue verified and working fine in release v1.9.3. Hence, closing this ticket.
