### ISSUE TITLE
Duplicate Facility Entries in Facility Group

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/facilities#321]
## Current behavior
The facility group displays duplicate entries for the facility that was added multiple times.

## Expected behavior
The facility group should display each facility only once, regardless of how many times it was added in the OMS.

## Steps to reproduce the issue
Open the OMS and navigate to the facilities page.
Add a facility group which is already linked with the facility.
In the App, go to facility group section and for the group(the same which was added in the OMS) view the linked facilities.
Observe the issue.

## Environment details
App version : v1.9.3
App environment : UAT

## Additional Information
![image](https://github.com/user-attachments/assets/c55027c5-b950-4edf-a8dd-5b2c56a4ed9c)

**Comment by dt2patel** [comment]
If a facility was added to a group multiple times to users, why would we not want to display it multiple times? Adding facility to group multiple times has downstream impact, so user also needs to know if facility is added multiple times when debugging those scenarios
