### ISSUE TITLE
Remove product store modal

### ISSUE THREAD

**Issue by dt2patel** [hotwax/facilities#47]
## What is the motivation for adding/enhancing this feature?

Show a list of all product stores with the option to select using checkboxes right inline.

<img width="542" alt="Screenshot 2023-11-30 at 4 42 40 PM" src="https://github.com/hotwax/facilities/assets/60128132/c12f70f9-a381-4240-ac16-64aae85f9f1b">

**Comment by k2maan** [comment]
Not required now as product stores also have actions associated with them.
