### ISSUE TITLE
Virtual Facilities

### ISSUE THREAD

**Issue by dt2patel** [hotwax/facilities#57]
## What is the motivation for adding/enhancing this feature?

Add a list view page for all facility groups with an option to add more.

3 queues will have special data attached to them, others will show 2 generic types of data.

Brokering Queue:
Order count: for created and approved orders
Next brokering: time delta of next time brokering will run for normal order

Pre-order + Backorder parking:
Order count: created and approved orders
Auto release: job in pending show toggle on

Here is a link to the Figma design:
https://www.figma.com/file/bVPRRw282CqGKMdbz7dciH/HC-Ionic-design-system?type=design&node-id=31354-32954&mode=design&t=gN9KHFVz0ZIax5Pz-4

**Comment by ravilodhi** [comment]
This feature is covered in the following PRs -
https://github.com/hotwax/facilities/pull/61
https://github.com/hotwax/facilities/pull/66
