### ISSUE TITLE
Bulk Fulfillment Settings Update and Refresh Issue

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/facilities#59]
## Current behavior
An unexpected behavior has been identified when updating fulfillment settings. Instead of making individual changes, the system is automatically applying updates in bulk. Furthermore, upon revisiting the facility details page, the changes made are inconsistently refreshing or not being reflected as intended.

## Expected behavior
The system should allow users to make individual updates to fulfillment settings without automatically applying changes in bulk. Additionally, changes made should persist and be accurately reflected upon revisiting the facility details page.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by ymaheshwari1** [comment]
@Dhiraj1405 Can you please check once, if you are able to reproduce this issue?

**Comment by dt2patel** [comment]
@Adameddy26 can you please review this issue and add jam link if relevant still

**Comment by Adameddy26** [comment]
Issue is working fine. Hence, closing the ticket.
