### ISSUE TITLE
Implement Option to Change Location Type for Facilities

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/facilities#78]
## What is the motivation for adding/enhancing this feature?
Currently, there is a need to introduce a feature that allows users to change the location type of a facility after it has been created. This enhancement will provide flexibility and accommodate changes in business requirements.

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by dt2patel** [comment]
<img width="506" alt="Screenshot 2023-12-13 at 11 17 50 PM" src="https://github.com/hotwax/facilities/assets/60128132/6f889daf-0613-4781-b2df-30e0f20543eb">
Added UI for this. We can pick this now

**Comment by ymaheshwari1** [comment]
From discussion:

```
Here type is parent type

Subtype is actual type

If user changes parent type then we will auto select the first sequence type facility of that parent. And save

Then user can change the actual type to move it to their desired value
```
