### ISSUE TITLE
Implement Automatic Indexing on Data Changes

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/facilities#80]
## What is the motivation for adding/enhancing this feature?
To enhance the efficiency and responsiveness of our system, we need to implement an automatic indexing mechanism that triggers whenever there is a change in the data. This will ensure that our search and retrieval processes remain optimized, providing users with real-time access to updated information.

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by ravilodhi** [comment]
Triggers for the auto-indexing of facilities/stores are done. Marking it as complete.
