### ISSUE TITLE
Add empty state when no product stores are linked to a facility

### ISSUE THREAD

**Issue by ymaheshwari1** [hotwax/facilities#96]
## Current behavior

When facility is not linked to any product store then simply the product store card is shown

## Expected behavior

There should be a message indication that there are no product stores linked to the facility.
`Product Store(s) not linked`

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version: 

## Additional information

![image](https://github.com/hotwax/facilities/assets/41404838/fc28a936-50f0-4cfe-976a-43edcb0fd7f9)

**Comment by dt2patel** [comment]
<img width="378" alt="Screenshot 2023-12-11 at 6 55 05 AM" src="https://github.com/hotwax/facilities/assets/60128132/702b8eff-93f2-4b34-8bd8-18f526a5f947">

If no product stores are linked, we should use this UI pattern that we are using for address and lat long
